/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LivingRouteImport } from './routes/living'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as BedroomRouteImport } from './routes/bedroom'
import { Route as BathroomRouteImport } from './routes/bathroom'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LivingRoute = LivingRouteImport.update({
  id: '/living',
  path: '/living',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const BedroomRoute = BedroomRouteImport.update({
  id: '/bedroom',
  path: '/bedroom',
  getParentRoute: () => rootRouteImport,
} as any)
const BathroomRoute = BathroomRouteImport.update({
  id: '/bathroom',
  path: '/bathroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom': typeof BathroomRoute
  '/bedroom': typeof BedroomRoute
  '/dining': typeof DiningRoute
  '/kitchen': typeof KitchenRoute
  '/living': typeof LivingRoute
  '/owner': typeof OwnerRoute
  '/reels': typeof ReelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom': typeof BathroomRoute
  '/bedroom': typeof BedroomRoute
  '/dining': typeof DiningRoute
  '/kitchen': typeof KitchenRoute
  '/living': typeof LivingRoute
  '/owner': typeof OwnerRoute
  '/reels': typeof ReelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom': typeof BathroomRoute
  '/bedroom': typeof BedroomRoute
  '/dining': typeof DiningRoute
  '/kitchen': typeof KitchenRoute
  '/living': typeof LivingRoute
  '/owner': typeof OwnerRoute
  '/reels': typeof ReelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bathroom'
    | '/bedroom'
    | '/dining'
    | '/kitchen'
    | '/living'
    | '/owner'
    | '/reels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bathroom'
    | '/bedroom'
    | '/dining'
    | '/kitchen'
    | '/living'
    | '/owner'
    | '/reels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bathroom'
    | '/bedroom'
    | '/dining'
    | '/kitchen'
    | '/living'
    | '/owner'
    | '/reels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BathroomRoute: typeof BathroomRoute
  BedroomRoute: typeof BedroomRoute
  DiningRoute: typeof DiningRoute
  KitchenRoute: typeof KitchenRoute
  LivingRoute: typeof LivingRoute
  OwnerRoute: typeof OwnerRoute
  ReelsRoute: typeof ReelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/living': {
      id: '/living'
      path: '/living'
      fullPath: '/living'
      preLoaderRoute: typeof LivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedroom': {
      id: '/bedroom'
      path: '/bedroom'
      fullPath: '/bedroom'
      preLoaderRoute: typeof BedroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom': {
      id: '/bathroom'
      path: '/bathroom'
      fullPath: '/bathroom'
      preLoaderRoute: typeof BathroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BathroomRoute: BathroomRoute,
  BedroomRoute: BedroomRoute,
  DiningRoute: DiningRoute,
  KitchenRoute: KitchenRoute,
  LivingRoute: LivingRoute,
  OwnerRoute: OwnerRoute,
  ReelsRoute: ReelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
